name: Deploy docker images to GCP Artifact registry
on:
    push:
      branches: ["main"]
 

jobs:
     deploy-gcp:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Use your numeric Project Number here, not the Project ID
          workload_identity_provider: 'projects/440081038764/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'githubserviceaccount@githubauth-495804.iam.gserviceaccount.com:generateAccessToken'
          contents: read
          pages: write
          id-token: write



            
      