  
  
  
  
  
  
  
  
  
  
  
  
  
  
name: Deploy to GCP
on:
    push:
        branches:
            - main
        
jobs:
    deploy-gcp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                # Use your numeric Project Number here, not the Project ID
                workload_identity_provider: 'projects/638495537867/locations/global/workloadIdentityPools/github/providers/github-portfolio'
                service_account: 'githubconnect@project-94e9628f-1e11-4518-969.iam.gserviceaccount.com:generateAccessToken'

                content: read
                page: write
                idtoken: write
                
