#create a name and tell github actions where to run our workflow
name: Testing indentation skills
#create when to run the workflow
on:
    push:
        branches:
            - main
# jobs are a collection of steps that will be executed as part of the workflow. Each job runs in a fresh instance of the virtual environment specified by runs-on. In this example, we specify that the job should run on the latest version of Windows.
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: checkout code in virtual environment
              uses: actions/checkout@v4
            - run: mpn ci
            - run: npm test
            - run: npm run build

              
                

